jobs:
  test:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn test
          name: Run Yarn tests
  lint:
    executor: node/default
    steps:
      - rome/check:
          pkg-manager: yarn
orbs:
  node: circleci/node@4.0.1
  rome: kbravh/rome-check@dev:alpha
version: 2.1
workflows:
  Test_app:
    jobs:
      - test
      - lint